name: Primer Pipeline CI/CD

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Mensaje de bienvenida
        run: echo "Bienvenido al primer pipeline CI/CD."

      - name: Fecha y hora de ejecución
        run: date

      - name: Versión de Git instalada
        run: git --version

      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar entorno Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar y ejecutar pruebas con Maven
        run: mvn test